version: "2"

services:
  web:
    build: docker_build/develop
    volumes:
      - ../../:/var/www/html/
      - ./dev-scripts/:/root/dev-scripts
    links:
      - db
      - wim_solr:solr
      - mailcatcher
    environment:
      - VIRTUAL_HOST=wim.dev
      - DRUPAL_SETTINGS=development
    ports:
      - "80"
    container_name: wim_web

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wim
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    container_name: wim_db

  mailcatcher:
    image: schickling/mailcatcher
    environment:
      - VIRTUAL_HOST=mailcatcher.wim.dev
      - VIRTUAL_PORT=1080
    ports:
      - "1080"
    container_name: wim_mailcatcher

  selenium:
    image: selenium/standalone-firefox-debug:2.53.0
    volumes:
      - ./behat/fixtures:/fixtures
    ports:
      - "4444"
      - "5900"
    container_name: wim_selenium
    cap_add:
      - NET_ADMIN
      - NET_RAW
    links:
      - web

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    container_name: wim_proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  wim_solr:
    image: mxr576/apachesolr-5.x-drupal-docker
    hostname: solr
    container_name: wim_solr
    restart: always
    environment:
      - SOLR_SOLR_MEM_SIZE=512m
      - PARTIAL_SEARCH_ENABLED=false
    ports:
      - "8983"

volumes:
  db_data:
